version: '3'
services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - "discovery.type=single-node"
        volumes:
            - "C:/Projects/training/lectures/2018/net-core-ecosystem/module25-docker/kiwi/elastic:/usr/share/elasticsearch/data"
            
    kibana:
        image: docker.elastic.co/kibana/kibana:6.4.1
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_URL=http://elastic:9200